export const locations = [
  {id: 1, label: "Colombo"},
  {id: 2, label: "Kandy"},
  {id: 3, label: "Galle"},
  {id: 4, label: "Ampara"},
  {id: 5, label: "Anuradhapura"},
  {id: 6, label: "Badulla"},
  {id: 7, label: "Batticaloa"},
  {id: 8, label: "Gampaha"},
  {id: 9, label: "Hambanthota"},
  {id: 10, label: "Jaffna"},
  {id: 11, label: "Kaluthara"},
  {id: 12, label: "Kegalle"},
  {id: 13, label: "Kilinochchi"},
  {id: 14, label: "Kurunagala"},
  {id: 15, label: "Mannar"},
  {id: 16, label: "Mathale"},
  {id: 17, label: "Mathara"},
  {id: 18, label: "Mullativu"},
  {id: 19, label: "Polonnaruwa"},
  {id: 19, label: "Puttalam"},
  {id: 19, label: "Rathnapura"},
  {id: 19, label: "Thrincomalee"},
  {id: 19, label: "Vavuniya"},

];
