export const locations = [
  {id: 1, label: "Kelaniya"},
  {id: 2, label: "Kiribathgoda"},
  {id: 3, label: "Gampaha"},
  {id: 4, label: "Wellawatta"},
  {id: 5, label: "Kaluthara"},
  {id: 6, label: "Katunayake"},
  {id: 7, label: "Monaragala"},
  {id: 8, label: "Mathara"},
  {id: 9, label: "Galle"},
  {id: 10, label: "Kandy"},
  {id: 11, label: "Negambo"},
  {id: 12, label: "Batticaloa"},
  {id: 13, label: "Rathnapura"},
  {id: 14, label: "Thangalle"},
  {id: 15, label: "Dehiwala"},
  {id: 16, label: "Colombo 1"},
  {id: 17, label: "Colombo 2"},
  {id: 18, label: "Colombo 3"},
  {id: 19, label: "Colombo 4"},
];
